server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - logging.yml
      - monitoring.yml
  cloud:
    openfeign:
      client:
        config:
          pg-simulator:
            connect-timeout: 3000
            read-timeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      pg-simulator:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
  retry:
    instances:
      pg-simulator:
        max-attempts: 2
        wait-duration: 1s
        retry-exceptions:
          - feign.RetryableException
        fail-after-max-attempts: true
springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local, test

pg-simulator:
  url: http://localhost:8082

payment:
  callback-url: http://localhost:8080/api/v1/payments/callback

---
spring:
  config:
    activate:
      on-profile: dev

pg-simulator:
  url: http://pg-simulator:8082

payment:
  callback-url: http://commerce-api:8080/api/v1/payments/callback

---
spring:
  config:
    activate:
      on-profile: qa

pg-simulator:
  url: http://pg-simulator:8082

payment:
  callback-url: http://commerce-api:8080/api/v1/payments/callback

---
spring:
  config:
    activate:
      on-profile: prd

pg-simulator:
  url: http://pg-simulator:8082

payment:
  callback-url: http://commerce-api:8080/api/v1/payments/callback

springdoc:
  api-docs:
    enabled: false